### ISSUE TITLE
How to extend to other LMs?

### ISSUE THREAD

**Issue by ethanjperez** [tonyzhaozh/few-shot-learning#2]
The README mentions that it's possible to use this codebase to test few-shot learning with any LM from the HuggingFace repo. Is this supported by the code directly, or if not, would you mind sharing pointers on how to extend the code to do so?

One particular question I had is why the `pad_token_id` for the model config variable needs to be set to the `eos_token_id` as in this [line](https://github.com/tonyzhaozh/few-shot-learning/blob/main/utils.py#L61). I understand that you are setting the PAD token to be the same token as the EOS token, but does it need to be set in the model config variable as well? I'm asking because other models like XLNet do not have `model.config.pad_token_id` set, and I'm wondering if I should override the default config.

**Comment by tonyzhaozh** [comment]
Hi Ethan,

Sorry for this very late reply. I'm guessing you've figure it out already (I saw your latest paper and codebase!).

For future reference: to add a new LM one would need to overwrite the "complete_gpt*" and "setup_gpt*" functions in utils.py, as you mentioned in the case of XLNet.

Cheers,
Tony
